### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#10]
The PFS should store its state when shutting down cleanly. This includes channels, channel balances and fees.

In the case of an unexpected shutdown the PFS can sync from the start.
 
## ToDo
- [x] Decide on datastore (decision: sqlite)
- [x] Store state of blockchain sync (maybe replace the blockchain syncing code with the more functional code from MS, see #230)
- [x] Store token networks and channel infos
- [x] Restore network graph before starting BC listening and matrix client
- [x] ~~Save Matrix syncing state~~ (not possible right now)

**Comment by karlb** [comment]
After #10, we can probably move to a shared implementation to handle `BlockchainState`, since both PFS and MS have to persists
* last_known_block
* token_network_addresses
* some metadata (chain_id, token_network_registry_address)
