### ISSUE TITLE
Honor monitor requests sent to MS in edge cases (crash, race condition)

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#17]
There are many cases where the MS might miss or ignore a monitor request (MR) sent by the client if not special precautions are taken to handle the edge cases:

- [x] The MS is down while a channel is closed
- [x] The MS does not know a channel is open at the time it receives a MR (moved to #26)
- [x] The channel has been closed just before the MR is received (moved to #29)
- [x] The MS state is lost because the process has been restarted
- [x] The MS state is inconsistent because the the system crashed during processing a block (moved to #32)

**Comment by karlb** [comment]
To make planning an discussion more specific, the remaining tasks have been split into #26, #29 and #32.
