### ISSUE TITLE
Add option for MS minimum reward

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#185]
## Problem Definition

As the MS I'd like to define a minimal reward that has to be given in order to provide my services.

### ToDos
- [x] Decide where to filter MRs based on reward (I'd argue that we want to do this in the MS, and still collect everything in the RC)
- [x] Add a command line flag for the minimal reward
- [x] Only call `monitor` when the reward of the MR is bigger than the threshold.

**Comment by Dominik1999** [comment]
We already have a flag `--service-fee` in `cli.py`
```
@click.option(
    '--service-fee',
    default=0,
    type=click.IntRange(min=0),
    help='Service fee which is required before processing requests',
)
```

**Comment by palango** [comment]
@Dominik1999 That's in the PFS, this issue is about the MS.

**Comment by Dominik1999** [comment]
ah sorry my mistake ...

**Comment by Dominik1999** [comment]
closed by https://github.com/raiden-network/raiden-services/pull/189
