### ISSUE TITLE
Pylint

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#280]
Enable more lints from pylint and get to the same or a stricter level than the Raiden client.

- [x] too-many-arguments
- [x] redefined-outer-name
- [x] too-many-instance-attributes
- [x] duplicate-code
- [x] too-many-locals
- [x] protected-access
- [x] ~~len-as-condition~~
- [x] redefined-builtin
- [x] too-many-return-statements
- [x] broad-except
- [x] invalid-name
- [x] unused-argument

Debatable:
- [x] ~~missing-docstring~~
- [x] ~~fixme~~
- [x] ~~unused-wildcard-import~~

**Comment by karlb** [comment]
The raiden client enables the following checks which are currently disabled in the services:
```ini
        # checks that are done with higher accuracy by mypy
        no-member,
        no-value-for-parameter,
        unexpected-keyword-arg,
        # style details that are handled by black
        bad-continuation,
```
The last one will have to be disabled for raiden when switching to black (https://github.com/raiden-network/raiden/issues/3738#issuecomment-487512882).

The first three one are IMO unnecessary noise when using mypy on the whole codebase. Does anyone have a counter example?

**Comment by palango** [comment]
> The first three one are IMO unnecessary noise when using mypy on the whole codebase

Then these might be removed from the client once they enable mypy. So I see no need to enable these unless someone can show some counter examples.

**Comment by karlb** [comment]
Raiden has two custom pylint checkers at https://github.com/raiden-network/raiden/tree/master/tools/pylint . Since those are not inside the raiden package, we can't use those without copying them.

Should we include those to have more consistent checks across repos, or do we consider those as checks for client specific problems?

Those checks are:
1. Does every `assert` have a message?
2. Is `gevent.joinall` always called with a set as parameter? This avoids calling it on collections which contain the same greenlet twice, which supposedly causes a deadlock.

**Comment by karlb** [comment]
Does anyone want to debate the debatable ones with me? Otherwise I'll treat those as wontfix.
