### ISSUE TITLE
Update docs/spec

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#410]
Add specific todos as we go

### ToDos
- [x] Update MS spec (https://github.com/raiden-network/spec/pull/318)
- [x] Update PFS Spec
- [x] Update service contracts spec
- [x] Document how to withdraw PFS fees
- [x] Document how to run a service bundle (probably a link to the service bundle is enough)

**Comment by karlb** [comment]
> Mention claim script for PFS
> Document how to withdraw PFS fees

Aren't those two the same? And isn't it covered by https://github.com/raiden-network/raiden-services/blob/master/docs/index.rst#claim-pathfinding-fees?

**Comment by palango** [comment]
True, I removed one.

My idea was more to document this for the service providers, so somewhere in the service bundle repo as well.
