### ISSUE TITLE
Merge service bundle with transport bundle

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#551]
We should merge the service bundle with the transport bundle to give people one thing to install.

- [x] Merge current services bundle (in `package/`) in the https://github.com/raiden-network/raiden-transport/ repo.
- [x] ~~Add guide for service registration~~ (tracked in #410)
- [x] ~~Add guide for PFS payouts~~ (tracked in #410)
- [x] Document sentry setup and recommend it (see https://github.com/raiden-network/raiden-service-bundle/issues/69)

**Comment by nlsdfnbch** [comment]
@palango / @konradkonrad - do you still need the droplet for this issue on DO?
