### ISSUE TITLE
Add profiling option

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#643]
We should be able to create profiling data both for PFSs running on services-dev.raiden.network and inside tests. Due to using gevent, we can't use the normal profiling tools.

- [x] Find out what Raiden is using for profiling, if that is not suitable for some reason, investigate https://pypi.org/project/GreenletProfiler/
- [x] Add option to save profile for running PFS (exclude startup from profile?)
- [x] Add a way to profile specific tests

Probably also useful:
- [x] Add option to save profile for running MS
- [x] Add option to save profile for running RC
- [ ] Log warnings when services reach high load
- [x] Profile one local PFS while running a scenario (see https://github.com/raiden-network/raiden-services/issues/651)

Sp 5
