### ISSUE TITLE
[Meta] PFS performance

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#665]
This issue tracks some known performance related problems in the PFS.

- [ ] [Use DisplayNameCache](https://github.com/raiden-network/raiden-services/issues/663)
- [ ] [Investigate performance of 'matrix_listener.follow_address_presence'](https://github.com/raiden-network/raiden-services/issues/644)
- [ ] [Check flame graph for easy optimizations](https://github.com/raiden-network/raiden-services/issues/651)

### Done

- [x] [Only join one matrix room](https://github.com/raiden-network/raiden-services/pull/657)
- [x] [PFS performance logging and tweaks](https://github.com/raiden-network/raiden-services/pull/656)
- [x] [Don't force presence update when receiving capacity update](https://github.com/raiden-network/raiden-services/pull/647)

**Comment by palango** [comment]
Related https://github.com/raiden-network/raiden-services/issues/651
