### ISSUE TITLE
Handle `PFSSwapUpdate` messages

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#850]
Sub-issue for https://github.com/raiden-network/raiden/issues/6506

## Description

For cross-token payments the nodes will announce their allowed swaps via `PFSSwapUpdate` messages. The PFS needs to handle them and incorporate the data into it's data store.

## Tasks

- [ ] Handle received `PFSSwapUpdate` messages
- [ ] Validate message as done for the other messages
- [ ] Update datastore with new information

## References
- https://github.com/raiden-network/raiden/issues/6511
